[package]
name = "aho-corasick"
version = "0.2.1"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Fast multiple substring searching with finite state machines."
documentation = "http://burntsushi.net/rustdoc/aho_corasick/"
homepage = "https://github.com/BurntSushi/aho-corasick"
repository = "https://github.com/BurntSushi/aho-corasick"
readme = "README.md"
keywords = ["string", "search", "text", "aho", "corasick"]
license = "Unlicense/MIT"

[lib]
name = "aho_corasick"

[[bin]]
name = "aho-corasick-dot"
test = false
doc = false
bench = false

[dependencies]
memchr = "0.1.*"

[dev-dependencies]
csv = "*"
docopt = "*"
quickcheck = "*"
rand = "*"
rustc-serialize = "*"

[[bench]]
name = "bench"
path = "benches/bench.rs"
test = false
bench = true
